-
  name: Install deps
  apt: name={{ item }} state=present
  with_items:
    - postgresql-server-dev-9.4
    - libpq-dev
    - ruby-dev
    - libsqlite3-dev

-
  name: kalibro_configurations setup
  command: bin/setup chdir=/vagrant/src/kalibro_configurations

-
  name: start kalibro_configurations
  shell: if [ -f tmp/pids/server.pid ]; then kill `cat tmp/pids/server.pid`; fi; sleep 2; rails s -b 0.0.0.0 -d -p 8083
  args:
    chdir: /vagrant/src/kalibro_configurations
