-
  name: Update cache 
  apt: update_cache=yes

-
  name: Upgrade packages
  apt: upgrade=dist

-
  name: install common packages
  apt: name={{ item }} state=present
  with_items:
    - vim
    - htop
